### PR TITLE
Feat: Trash grid view

### PR DESCRIPTION
**Pull request by Khallekan**
# Description

Initial layout for the trash grid view. To view navigate to the trash section and click the grid icon in the top right corner. Delete and restore functionality yet to be added.

### CODE REVIEW

**Comment by Khallekan** [comment]
@omzi please review

**Comment by omzi** [comment]
Apologies @Khallekan. Please pull in new changes & resolve any conflict that might arise.

**Comment by Khallekan** [comment]
@omzi now up to date

**Comment by omzi** [comment]
Apologies again 🙏🏽 @Khallekan. @Nkechi-Christabel worked on the trash section, so there's a new merge conflict 😬. Please could you handle that again 🙏🏽 ? Thanks.

**Comment by omzi** [comment]
Please tag me in the channel @Khallekan. I don't see notifs here in time. I'll merge ASAP.

**Pull request closed without merging**
