### PR TITLE
search files by size route issue #68

### LINKED ISSUE #68: Search for files by size
As a user, I want to be able to search for files by size to help me reach the file quicker.

### PR DESCRIPTION
**Pull request by afeezdev**
# Description

A route to search files by size 

> Fixes #68

# How Has This Been Tested?

Tested this locally on my PC using the following testing tools:
> 2. Dummy Data 
> 3. Postman

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no lint warnings

### CODE REVIEW

**Review by omzi — CHANGES_REQUESTED** [review]
@afeezdev You do know we're not using MongoDB right? Please check out other file controller functions & see how others are doing their stuff.

https://github.com/zurichat/zc_plugin_company_files/blob/19001e8e8408026d91f5633ea5d04c44239ce6d6/backend/controllers/file.controller.js#L149

**Comment by afeezdev** [comment]
I've made changes as earlier pointed out

**Comment by afeezdev** [comment]
I've done dthe corrections, kindly check again

**Review by omzi — APPROVED** [review]
Good work. It works but is not quite flexible as explained.

**Pull request merged**
